-- Only explicit production projections are browser-readable. All writes are backend-only.
alter table public.production_metadata enable row level security;
alter table public.memory_state enable row level security;
alter table public.job_leases enable row level security;
alter table public.job_runs enable row level security;
alter table public.post_decisions enable row level security;
alter table public.delivery_ledger enable row level security;
alter table public.weeks enable row level security;
alter table public.life_events enable row level security;
alter table public.usage_history enable row level security;
alter table public.settings enable row level security;
alter table public.errors enable row level security;
alter table public.public_state_snapshots enable row level security;
alter table public.public_songs enable row level security;
alter table public.public_media enable row level security;
alter table public.contacts enable row level security;
alter table public.conversations enable row level security;
alter table public.mentions enable row level security;
alter table public.reply_candidates enable row level security;
alter table public.x_account_identities enable row level security;
alter table public.x_read_cursors enable row level security;
drop policy if exists "anon reads published production snapshots" on public.public_state_snapshots;
drop policy if exists "anon reads active production songs" on public.public_songs;
drop policy if exists "anon reads active production media" on public.public_media;
create policy "anon reads published production snapshots" on public.public_state_snapshots for select to anon using(environment='production' and published);
create policy "anon reads active production songs" on public.public_songs for select to anon using(environment='production' and active);
create policy "anon reads active production media" on public.public_media for select to anon using(environment='production' and active);
revoke all on all tables in schema public from anon,authenticated;
grant usage on schema public to anon,authenticated,service_role;
grant select on public.public_state_snapshots,public.public_songs,public.public_media to anon,authenticated;
grant all on all tables in schema public to service_role;
grant usage,select on all sequences in schema public to service_role;
