-- Atomic staging-only operations. Service role only; fixed search_path.
create or replace function public.acquire_job_lease(p_name text,p_owner text,p_ttl_seconds integer default 300) returns boolean language plpgsql security definer set search_path=public,pg_temp as $$ begin if p_ttl_seconds<1 or p_ttl_seconds>3600 then raise exception 'invalid lease ttl'; end if; insert into job_leases(name,owner,expires_at,heartbeat_at) values(p_name,p_owner,now()+make_interval(secs=>p_ttl_seconds),now()) on conflict(name) do update set owner=excluded.owner,expires_at=excluded.expires_at,heartbeat_at=now() where job_leases.expires_at<=now() or job_leases.owner=excluded.owner; return found; end $$;
create or replace function public.heartbeat_job_lease(p_name text,p_owner text,p_ttl_seconds integer default 300) returns boolean language plpgsql security definer set search_path=public,pg_temp as $$ begin update job_leases set expires_at=now()+make_interval(secs=>p_ttl_seconds),heartbeat_at=now() where name=p_name and owner=p_owner and expires_at>now(); return found; end $$;
create or replace function public.release_job_lease(p_name text,p_owner text) returns boolean language plpgsql security definer set search_path=public,pg_temp as $$ begin delete from job_leases where name=p_name and owner=p_owner; return found; end $$;
create or replace function public.save_memory_cas(p_expected_version bigint,p_value jsonb) returns bigint language plpgsql security definer set search_path=public,pg_temp as $$ declare next_version bigint; begin update memory_state set value=p_value,version=version+1,updated_at=now() where singleton and version=p_expected_version returning version into next_version; if next_version is null then raise exception 'memory version conflict' using errcode='40001'; end if; return next_version; end $$;
create or replace function public.commit_run_decision(p_run_id text,p_action text,p_reason text,p_snapshot jsonb,p_expected_memory_version bigint,p_memory jsonb,p_category text default null,p_motif text default null,p_event_id text default null,p_song_id text default null,p_media_id text default null,p_include_url boolean default false) returns bigint language plpgsql security definer set search_path=public,pg_temp as $$ declare next_version bigint; begin update job_runs set status='decided',decision=p_snapshot where run_id=p_run_id and status='running'; if not found then raise exception 'run state conflict' using errcode='40001'; end if; insert into post_decisions(run_id,action,reason,snapshot,category,motif,event_id,song_id,media_id,include_url) values(p_run_id,p_action,p_reason,p_snapshot,p_category,p_motif,p_event_id,p_song_id,p_media_id,p_include_url); update memory_state set value=p_memory,version=version+1,updated_at=now() where singleton and version=p_expected_memory_version returning version into next_version; if next_version is null then raise exception 'memory version conflict' using errcode='40001'; end if; return next_version; end $$;
drop function if exists public.reset_staging_state(text);
create function public.reset_staging_state(p_confirmation text) returns boolean language plpgsql security definer set search_path=public,pg_temp as $$ begin if p_confirmation<>'RESET pandausagies-v2-staging' then raise exception 'staging reset confirmation mismatch'; end if; if not exists(select 1 from staging_metadata where singleton and environment='staging') then raise exception 'not a staging database'; end if; delete from public_state_snapshots; delete from usage_history; delete from delivery_ledger; delete from post_decisions; delete from weeks; delete from errors; delete from life_events; delete from job_runs; delete from job_leases; delete from settings; update memory_state set version=0,value='{}'::jsonb,updated_at=now() where singleton; return true; end $$;
revoke all on function public.acquire_job_lease(text,text,integer),public.heartbeat_job_lease(text,text,integer),public.release_job_lease(text,text),public.save_memory_cas(bigint,jsonb),public.commit_run_decision(text,text,text,jsonb,bigint,jsonb,text,text,text,text,text,boolean),public.reset_staging_state(text) from public,anon,authenticated;
grant execute on function public.acquire_job_lease(text,text,integer),public.heartbeat_job_lease(text,text,integer),public.release_job_lease(text,text),public.save_memory_cas(bigint,jsonb),public.commit_run_decision(text,text,text,jsonb,bigint,jsonb,text,text,text,text,text,boolean),public.reset_staging_state(text) to service_role;
