-- pandausagies V2 staging memory schema. Idempotent; contains no credentials.
create table if not exists public.staging_metadata (singleton boolean primary key default true check(singleton), environment text not null default 'staging' check(environment='staging'), schema_version integer not null default 1, updated_at timestamptz not null default now());
insert into public.staging_metadata(singleton) values(true) on conflict do nothing;
create table if not exists public.memory_state (singleton boolean primary key default true check(singleton), environment text not null default 'staging' check(environment='staging'), version bigint not null default 0, value jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now());
insert into public.memory_state(singleton,value) values(true,'{}'::jsonb) on conflict do nothing;
create table if not exists public.job_leases (name text primary key, environment text not null default 'staging' check(environment='staging'), owner text not null, expires_at timestamptz not null, heartbeat_at timestamptz not null default now());
create table if not exists public.job_runs (run_id text primary key, environment text not null default 'staging' check(environment='staging'), mode text not null check(mode in ('observe','dry_run','send')), status text not null check(status in ('running','decided','succeeded','failed','safe_stopped')), started_at timestamptz not null default now(), finished_at timestamptz, decision jsonb, error text);
create table if not exists public.post_decisions (id bigint generated always as identity primary key, run_id text not null unique references public.job_runs(run_id) on delete cascade, environment text not null default 'staging' check(environment='staging'), action text not null check(action in ('post','skip')), category text, motif text, event_id text, song_id text, media_id text, include_url boolean not null default false, reason text not null, snapshot jsonb not null, decided_at timestamptz not null default now());
create table if not exists public.delivery_ledger (idempotency_key text primary key, run_id text not null unique references public.job_runs(run_id), environment text not null default 'staging' check(environment='staging'), kind text not null check(kind in ('post','week')), status text not null check(status in ('candidate','sending','sent','failed','planned','published')), payload jsonb not null, external_id text unique, updated_at timestamptz not null default now());
create table if not exists public.weeks (week_number integer primary key check(week_number>0), environment text not null default 'staging' check(environment='staging'), run_id text not null unique references public.job_runs(run_id), body text not null, song_id text, media_id text, status text not null check(status in ('planned','published','failed','simulated')), finalized_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.life_events (id text primary key, environment text not null default 'staging' check(environment='staging'), value jsonb not null, status text not null check(status in ('open','closed','forgotten')), updated_at timestamptz not null default now());
create table if not exists public.usage_history (id bigint generated always as identity primary key, environment text not null default 'staging' check(environment='staging'), kind text not null check(kind in ('song','media','motif')), item_id text not null, run_id text references public.job_runs(run_id), used_at timestamptz not null default now());
create table if not exists public.settings (key text primary key, environment text not null default 'staging' check(environment='staging'), value jsonb not null, updated_at timestamptz not null default now());
create table if not exists public.errors (id bigint generated always as identity primary key, environment text not null default 'staging' check(environment='staging'), run_id text, severity text not null check(severity in ('warning','critical')), message text not null, context jsonb, occurred_at timestamptz not null default now());
-- Browser-readable projections only. Private memory never belongs here.
create table if not exists public.public_state_snapshots (id bigint generated always as identity primary key, environment text not null default 'staging' check(environment='staging'), payload jsonb not null, published boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.public_songs (id text primary key, environment text not null default 'staging' check(environment='staging'), title text not null, youtube_video_id text not null, youtube_url text not null, release_info jsonb, active boolean not null default true);
create table if not exists public.public_media (id text primary key, environment text not null default 'staging' check(environment='staging'), public_url text not null, alt_text text not null, active boolean not null default true);
-- Phase 7 private X read-only memory. Never exposed through PUBLIC STATE.
create table if not exists public.contacts (x_user_id text primary key, environment text not null default 'staging' check(environment='staging'), current_username text not null, display_name text not null, first_seen_at timestamptz not null, last_seen_at timestamptz not null, interaction_count integer not null default 1 check(interaction_count>0), short_conversation_summary text not null default '', automation_opt_out boolean not null default false);
create table if not exists public.conversations (conversation_id text primary key, environment text not null default 'staging' check(environment='staging'), x_user_id text not null references public.contacts(x_user_id) on delete cascade, summary text not null default '', first_seen_at timestamptz not null, last_seen_at timestamptz not null);
create table if not exists public.mentions (x_post_id text primary key, environment text not null default 'staging' check(environment='staging'), author_id text not null references public.contacts(x_user_id) on delete cascade, username text not null, display_name text not null, text text not null, created_at timestamptz not null, conversation_id text references public.conversations(conversation_id) on delete cascade, referenced_post_id text, in_reply_to_user_id text, retrieved_at timestamptz not null default now(), status text not null check(status in ('received','classified','candidate_generated','awaiting_review','ignore','needs_human','sensitive','opted_out','spam')), raw_minimal jsonb not null default '{}'::jsonb);
create table if not exists public.reply_candidates (id bigint generated always as identity primary key, environment text not null default 'staging' check(environment='staging'), x_post_id text not null unique references public.mentions(x_post_id) on delete cascade, body text, classification text not null check(classification in ('candidate','ignore','needs_human','sensitive','opted_out','spam')), status text not null check(status in ('awaiting_review','ignored','needs_human','suppressed')), created_at timestamptz not null default now());
create table if not exists public.x_account_identities (handle text primary key, environment text not null default 'staging' check(environment='staging'), x_user_id text not null unique, current_username text not null, display_name text not null, resolved_at timestamptz not null, updated_at timestamptz not null default now());
create table if not exists public.x_read_cursors (key text primary key, environment text not null default 'staging' check(environment='staging'), last_seen_mention_id text, last_successful_x_read_at timestamptz, last_status text not null default 'never', api_call_count bigint not null default 0, error_count bigint not null default 0, retry_after timestamptz, updated_at timestamptz not null default now());
-- Phase 7.1 migration: Developer Console account metadata never belongs in a read cursor.
alter table public.x_read_cursors drop column if exists x_user_id;
alter table public.x_read_cursors drop column if exists current_username;
create index if not exists job_runs_started_at_idx on public.job_runs(started_at desc);
create index if not exists usage_history_kind_used_at_idx on public.usage_history(kind,used_at desc);
create index if not exists errors_occurred_at_idx on public.errors(occurred_at desc);
create index if not exists public_snapshots_created_at_idx on public.public_state_snapshots(created_at desc) where published;
create index if not exists mentions_conversation_created_idx on public.mentions(conversation_id,created_at,x_post_id);
create index if not exists mentions_author_created_idx on public.mentions(author_id,created_at desc);
